spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      url: jdbc:mysql://k8c106.p.ssafy.io:3306/festo?serverTimezone=Asia/Seoul
      password: 1234

  jpa:
    hibernate:
       ddl-auto: update
    show-sql: true
    generate-ddl: true

jwt:
  secret: 6riw64uk66a87JeG64qU7LaV7KCc66W87JyE7ZWc7Iqk66eI7Yq47Jik642U

cloud:
  aws:
    credentials:
      accessKey: AKIAXI6LVK5FS6IMGTUR
      secretKey: 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
    s3:
      bucket: festo-s3
      dir: festo
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'
